[toolchain]
profile = "minimal"
# use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
channel = "nightly-2024-09-15"
components = ["rustfmt", "rustc", "rust-std", "rust-src", "cargo", "clippy", "llvm-tools-preview"]
targets = ["riscv64gc-unknown-none-elf"]
