[toolchain]
profile = "minimal"
channel = "nightly-2024-05-01"
components = [
    "rustfmt",
    "rustc",
    "rust-std",
    "rust-src",
    "cargo",
    "clippy",
    "llvm-tools-preview",
]
targets = ["riscv64gc-unknown-none-elf"]
