[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = ["-Clink-arg=-T../linker-rv.ld", "-Cforce-frame-pointers=yes"]

[target.loongarch64-unknown-linux-gnu]
linker = "loongarch64-linux-gnu-gcc"
rustflags = [
    "-Clink-arg=-TNoAxiom/user/apps/linker-la.ld",
    "-Clink-arg=-nostdlib",
    "-Clink-arg=-static",
]
