[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/YuXuaann/ext4_rs-async-smp"]
git = "https://github.com/YuXuaann/ext4_rs-async-smp"
replace-with = "vendored-sources"

[source."git+https://github.com/YuXuaann/virtio-drivers-async"]
git = "https://github.com/YuXuaann/virtio-drivers-async"
replace-with = "vendored-sources"

[source."git+https://github.com/os-module/kernel-sync.git"]
git = "https://github.com/os-module/kernel-sync.git"
replace-with = "vendored-sources"

[source."git+https://github.com/os-module/plic"]
git = "https://github.com/os-module/plic"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = ["-Clink-arg=-Tlib/.ld/linker-rv.ld", "-Cforce-frame-pointers=yes"]

[target.loongarch64-unknown-linux-gnu]
linker = "loongarch64-linux-gnu-gcc"
rustflags = [
    "-Ctarget-feature=-ual",
    "-Clink-arg=-Tlib/.ld/linker-la.ld",
    "-Clink-arg=-nostdlib",
    "-Clink-arg=-static",
]
